[package]
name = "challenge_24"
version = "0.1.0"
edition = "2021"

[dependencies]
fraction = "0.15.3"
minijinja = { version = "2.5.0", features = ["loader"] }
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.215"
